<?php require_once __DIR__ . '/../basic/header.phtml'; ?>
<form action="home/tryLogin" method="post" class="form container text-center p-3">
    <?php
        echo isset($error)? '<div class="alert alert-warning">
            <h5>Błąd logowania!</h5>
            Nie poprawne dane logowania!
        </div>' : '';
    ?>
    <label>
        Nick: 
        <input type="text" name="username" id="" class="form-control" autofocus>
    </label>
    <br>
    <label>
        Hasło: 
        <input type="password" name="password" id="" class="form-control">
    </label>
    <br>
    <input type="submit" value="Zaloguj" class="btn btn-link">
    <br>
    <a href="home/register" class="btn btn-link">albo zarejestruj</a>
</form>
<?php require_once __DIR__ . '/../basic/footer.phtml'; ?>