<?php require_once __DIR__ . '\basic/header.phtml'; ?>
<div class="row">
    <div id="listOfUsersInRoom" class="col-md-1">
        <ul class="list-group">
            <li class="list-group-item">mrkamis</li>
            <li class="list-group-item">mrkamis</li>
            <li class="list-group-item">mrkamis</li>
            <li class="list-group-item">mrkamis</li>
            <li class="list-group-item">mrkamis</li>
        </ul>
    </div>
    <div id="mainContainerWithCards" class="col-md-9">
        <div class="row">
            <div class="card bg-dark col-md-3 m-1 text-light">
                <h5>Czarna</h5>
            </div>
        </div>
        <div class="row">
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
            <div class="card bg-light col-md-2 m-1 text-dark">
                Biała
            </div>
        </div>
    </div>
    <div class="chat" class="col-md-2">
        Chat
    </div>
</div>
<?php require_once __DIR__ . '\basic/footer.phtml'; ?>